// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7c0eDfGzJynAFUyowmQukuTd_VjFcFw',
    appId: '1:583557751613:web:7ee7f3cd2fc7530edd5b54',
    messagingSenderId: '583557751613',
    projectId: 'libre-4c3a0',
    authDomain: 'libre-4c3a0.firebaseapp.com',
    storageBucket: 'libre-4c3a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjjUCuYcsEUje-ZkQTz1rCZAzw2vwnoI',
    appId: '1:583557751613:android:fbd7a1db95d781fcdd5b54',
    messagingSenderId: '583557751613',
    projectId: 'libre-4c3a0',
    storageBucket: 'libre-4c3a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3XUqdAz8AIgygMgzYViyb4C_hbmlCr4',
    appId: '1:583557751613:ios:3d5f3be7456c8359dd5b54',
    messagingSenderId: '583557751613',
    projectId: 'libre-4c3a0',
    storageBucket: 'libre-4c3a0.firebasestorage.app',
    iosBundleId: 'com.example.yorozuya',
  );
}
